### ISSUE TITLE
Error 500 when update_checker is enabled

### ISSUE THREAD

**Issue by VGirol** [oneduo/nova-file-manager#432]
Here is part of the stacktrace :

version_compare(): Argument #2 ($version2) must be of type string, null given at vendor/oneduo/nova-file-manager/src/Http/Controllers/ToolController.php:53
[stacktrace]
#0 vendor/oneduo/nova-file-manager/src/Http/Controllers/ToolController.php(53): version_compare('v0.12.3', NULL, '<')
#1 vendor/laravel/framework/src/Illuminate/Cache/Repository.php(396): Oneduo\\NovaFileManager\\Http\\Controllers\\ToolController->Oneduo\\NovaFileManager\\Http\\Controllers\\{closure}()
#2 vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(429): Illuminate\\Cache\\Repository->remember('nova-file-manag...', 86400, Object(Closure))
#3 vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(355): Illuminate\\Cache\\CacheManager->__call('remember', Array, key: 'nova-file-manag...', ttl: 86400, callback: Object(Closure))
#4 vendor/oneduo/nova-file-manager/src/Http/Controllers/ToolController.php(46): Illuminate\\Support\\Facades\\Facade::__callStatic('remember', Array, key: 'nova-file-manag...', ttl: 86400, callback: Object(Closure))

**Comment by Rezrazi** [comment]
Hey @VGirol 
we rely on GitHub to determine the upstream latest version
Can you please check if this endpoint is working in your system/server? 
`GET https://api.github.com/repos/oneduo/nova-file-manager/releases/latest`

**Comment by VGirol** [comment]
I've checked this endpoint and here is the response i receive :

{"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

I think i've found the problem ;-)

Thanks for your help

**Comment by mikaelpopowicz** [comment]
Hi @VGirol 

A fix has been released.

Cheers.

**Comment by VGirol** [comment]
Great, thanks !
